### PR TITLE
Pull Request MediaFileToMovieConvert

### PR DESCRIPTION
**Pull request by Norskan**
did some mayor refactoring of MediaHandler, StringStuff, MediaInfoGetter, MediaInfo.

pease @codemaster3000, @fla91 please tell me what you think about it, should you not approve of the refactoring we can throw the branch away again. ;)
- [ ] ~~write unit test~~
- [x] finish code refactoring (clear all TODO(refector) tags)
- [ ] verify

### CODE REVIEW

**Comment by Norskan** [comment]
please verify so we can merge this as soon as possible!

**Comment by communityFabian** [comment]
Checked the code and it looks fine. But here some possible improvement suggestions for the package structure:

filescanner stuff --> give it its own package ("mediascanner") together with sub "util" package and separate it from the medialibrary services apis (tmdb, medinfo, xrel). Change package "medialibrary" to "mediaservices"

application package --> looks good...except maybe rename the "converter" class to something like "MediadataReader" or similiar. Converter sounds confusing. In setup we can give the tasks an own sub-package as there will be soon more loading tasks

database package --> ok.

**Comment by Norskan** [comment]
###### filscanner stuff

 okay seams reasonable i will do that.

###### application package

okay, i forgot to replace the convert methode parameter File with MediaInfo then the converter would make more sense because you convert from one format to the other. But i can also rename it to MediadataReader if you prefer that. I will make a sub-pakage for the loading tasks

**Comment by Norskan** [comment]
- Renamed medialibraries to scrabs as discussed in https://github.com/codemaster3000/MovieManager/issues/10 
- moved filescanner and blackmediamanager.mediafile.uitl to  blackmediamanager.mediascanner
- renamed Converter to MovieReader this should be much clearer now

if you @codemaster3000 would have a finall look over it i will merge it.

**Comment by communityFabian** [comment]
its verified

**Pull request merged**
